Publish token env var (#23)

diff --git a/.github/actions/publish/action.yml b/.github/actions/publish/action.yml
--- a/.github/actions/publish/action.yml
+++ b/.github/actions/publish/action.yml
@@ -15,9 +15,14 @@ runs:
       if: github.ref_type == 'tag'
       env:
         GH_TOKEN: ${{ github.token }}
+        VSCE_PAT: ${{ inputs.VSCE_PAT }}
       run: |
         if [ -z "${GITHUB_REF_NAME:-}" ]; then
-          echo "GITHUB_REF_NAME is not set..."
+          echo "ERROR: GITHUB_REF_NAME is not set..." >&2
+          exit 1
+        fi
+        if [ -z "${VSCE_PAT:-}" ]; then
+          echo "ERROR: VSCE_PAT is not set" >&2
           exit 1
         fi
         gh release upload "$GITHUB_REF_NAME" bats-test-runner-*.vsix
